### ISSUE TITLE
Add "test/helpers" to "start" branch

### ISSUE THREAD

**Issue by ShMcK** [kentcdodds/react-ava-workshop#10]
### Issue

The first steps of the tutorial fail as the "test/helpers/setup-test-env.js" file is missing on the "start" branch.
### Steps to reproduce:

``` shell
git clone https://github.com/kentcdodds/react-ava-workshop
cd react-ava-workshop
git checkout start
npm install --save-dev ava
npm i
npm run test
```
### Resulting Error:

```
Error: Could not resolve required module './test/helpers/setup-test-env.js'
    at /Users/shmck/Desktop/react-ava-workshop/node_modules/ava/api.js:31:10
    at Array.map (native)
    at new Api (/Users/shmck/Desktop/react-ava-workshop/node_modules/ava/api.js:28:54)
    at Object.<anonymous> (/Users/shmck/Desktop/react-ava-workshop/node_modules/ava/cli.js:131:11)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```
### Possible solutions:
1. add instructions for setting up test helpers
2. add "test/helpers/setup-test-env.js" to the "start" branch

**Comment by ShMcK** [comment]
Better solution: remove lines from the initial "package.json".

``` js
"ava": {
    "babel": "inherit",
    "require": [
      "./test/helpers/setup-test-env.js"
    ]
  },
```

**Comment by kentcdodds** [comment]
Could you file a PR?
